# Generated by Django 2.0.7 on 2018-08-03 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import games.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('O', 'Ongoing'), ('W', 'White Victory'), ('B', 'Black Victory')], default='O', max_length=1)),
                ('history', models.CharField(default='', max_length=240)),
                ('label', models.CharField(default=games.models.get_random_label, max_length=12, unique=True)),
                ('black_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='black', to=settings.AUTH_USER_MODEL)),
                ('white_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='white', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
