# Generated by Django 2.0.7 on 2018-08-07 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_challenge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='receiver',
        ),
        migrations.DeleteModel(
            name='Challenge',
        ),
    ]
